name: 'enclave-setup-action'
description: 'Sets up Enclave in a GitHub action to allow connectivity to your Enclave network.'
author: 'Enclave Networks'
inputs:
  channel:
    required: false
    description: 'Change to unstable to use the latest RC'
    default: 'stable'
  enrolment-key:
    required: true
    description: 'The enrolment key to use when enrolling the system'
runs:
  using: 'node12'
  main: 'dist/setup/index.js'
  post: 'dist/post/index.js'
