name: 'enclave-setup'
description: 'Sets up Enclave in a GitHub action to allow connectivity to your Enclave network.'
author: 'Enclave Networks'
inputs:
  channel:
    required: false
    description: 'Change to unstable to use the latest RC'
    default: 'stable'
  enrolment-key:
    required: true
    description: 'The enrolment key to use when enrolling the system'
  orgId:
    required: true
    description: 'The organisation ID for your Enclave Organisation.'
  apiKey:
    required: true
    description: 'An API key used to remove the system from your Enclave account when the job ends.'
runs:
  using: 'node12'
  main: 'dist/setup/index.js'
  post: 'dist/post/index.js'
